apiVersion: v1
kind: Service
metadata:
  name: book-app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: book-app 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app 
  template:
    metadata:
      labels:
        app: book-app 
    spec:
      containers:
        - image: <ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/book-app:latest 
          name: book-app 
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: book-app-hpa
  namespace: default
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 15
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-app-deployment